import type { Metadata } from "next";
import { Bebas_Neue, DM_Sans } from "next/font/google";
import "./globals.css";

const bebas = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bebas",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Metamorfit [ALPHA] | Your High-Performance Metabolic Blueprint",
  description: "Get a personalized metabolic plan generated by AI. Optimized for fat loss, muscle gain, and peak performance.",
  openGraph: {
    title: "Metamorfit [ALPHA] | AI-Powered Metabolic Planning",
    description: "Stop guessing. Get a science-based metabolic blueprint tailored to your biology and goals.",
    url: "https://metamorfit.pro",
    siteName: "Metamorfit [ALPHA]",
    images: [
      {
        url: "https://metamorfit.pro/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Metamorfit Metabolic Blueprint",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Metamorfit [ALPHA] | AI Metabolic Planning",
    description: "Your personalized metabolic blueprint, delivered instantly.",
    images: ["https://metamorfit.pro/og-image.jpg"],
  },
  robots: "index, follow",
};

export const viewport: import("next").Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${bebas.variable} ${dmSans.variable}`}>
      <body className="antialiased bg-[#050505] text-[#e8e2d5] font-body" suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
